export const OTT_SEED_DATA = [
  {
    "title": "#좀비를 찾습니다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/IwxYT-dShtb8cY1O52GrPPuMGEkoDc7p0rm-aiCP7paxc-QvPiIWmexC48nkYMpXZbSiQ8xqDd1We1nXVwmKfl4SeF79f9avIC89YOraatO4QcssF_MzH9QYOk6AsBrXjXy-yQEh-Uyt8u-6MWUq0g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "DARK MACHINE THE ANIMATION",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/7UDPEDUq9rlv3r1u2jv5OetvKvwDh1rnVJZmxUWrqXztDyzgpQP4GHbj4s3mCG2rKzLQdktg5nCG3_FvDUL8dLUhWIsQJrKeo0NJpsqUwykedQFNDjZ_OgBmxRVe22lwNHSSoHr_3gDjAUzGlqnzbQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "FX 전사 쿠루미/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/PiI1YVbqmpKzDikKycwax5K8w7QBaGP875wzLKSGMyEEGLKvv3wrtc7gb2nG6VtkCeWhUAO_YPCz4iT7Q4ElHwu7wc9Qsql-8jiSfMGdeEkn7nx6h6MxnUBCEIp9Dvw1V8IDvfN8ZKXKXbBEzNQ9Xw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "GROTESQQQUE -그로테스크-",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/ssCc8Q5oQZWwebdka1MPP5SuQuKcbL4tdimneQC6VEfAUv0vl06Yh0umTJ3b97zVBgnyi0f_pasYXvXN9igume5BmafBX36-t_I_78KgJXAubyNF2AO3D0QF5e5fx3_yLxvUhBk62sEPwIxhkCduXg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "TANK CHAIR -탱크체어-/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/xvGuRwqNt1SkdtuKD9B9hsxMXUuWH2NvLoysamJpBoYEneR6bDYNB7BzfZixfVoSWd2BVmPm2nPpmkZFqZ7dFpH3iGZkBp06owZwqvY6U9UHwvjrBV47OId0wGp1dvzl45uocRcV3xNPvxAth0xMzg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "개구리 중사 케로로☆",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/b9C4LLsMGPBGMOfploIajfAce2wnHxBPoHVSqpSRLNzuVgEx5N2LQw8jUyMnwfHTm_GIABjDercVscfcHTFsxa2MPbF0lMNAGao8thqrqlLg0ZmudPMFQiWrjzmc5jKU8Izfjx_2SJxejkqB7vX96Q.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "걸즈 앤 판처 좀 더 러브러브 작전입니다!/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/8mkgDPJf2dK7YlQqQCxf_zsSfpvdyOHXC5kuXuEO3OwUx6YUBgCTVlVGOtcVKe9By81cG2CuqZkv_F1_do_ZcXZmuVJyUeoTf8qGpcddSPRdiaabyt9c-MHHp5_PBpkGVFaYQOrU6HuI_IpELCBFhw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "걸즈 앤 판처 최종장 제5화",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/JmRBs951dOHHf7v46kCzWDNIAnVlBY_yQv0oSvJFeSBU6Ey9pqIkZKJpwyw0lpTxAMWh99H6_oMJDnO7KX6T9P9nn6pMxf2bmdkmpGakiQoqcpysWX0-u6mNPYe4bFs6dFrJy18b9bzEeMnBpwExiA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "공포 스쿨/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/roLDpozhN9XhyUdOFzS2bCM5yDhdf6JtTvgbdPwOFrOdMDsgEKwlivQnYuCzM9vq0oVv4UK29ayzAsGqOtHy5CK8NEHlV2UfCC4wzezRoEPv3oEI2vtjvovk9McF2CsLJqNrlVDKoo9Z3MzeuFKSHQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "귀환자의 마법은 특별해야 합니다(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/y7Yo1hjDcsUjFfhDsKv4HiaHkLaL-MSXrXw2zHI1BWbWu06x6dMbOaWPotnzeyFLZTAB-ygHKvNJvcru_LMu5a7mbBon1jIcxuWLl-_frYlPKm_xGX6Fg1bIe1bMMSP0MZ3jcbRa-QrL8ZrY2MN-IQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "그 어디보다 먼 곳에 있는 너에게/애니메이션",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/8WCy4DYoT_9ikB5CkCmI-lgK_Be7FYWx-Ex8TgdLw4oQdOlvilnd6WwQfs0goizUTSeqfl2bYV1VwuI5eCBRZJ-nF3qfjqU6X6kh-AMepIl3fhbhkwZ0Jqr6q6iDx0KFZCXe_Glsl3kwLY0KEvXY8w.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "극장판 약사의 혼잣말 망비의 비보",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/xVbzdHcrBpoanIL9C9HHN82VzB-N1SCQwJX31s7I-b2F6N5pLKUH1CIiZh6Q2SlnD8VuJ7e9CMKV9FlOELQOuVEfN9hazY8MJNmp0HtaLBcyq1V7dfBrhX7jdOcvWCSm0jMwH96cb_z6CSaHc3zciw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "나약MAX 영애인데 수완가 약혼자와 내기를 하고 말았다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/Xwu5ArqftmSC49c5OqhesW9WETWaT6UePzW1nD_GZ3wqBu0uTK3FvO67X5Xr2xSN0cyScFBV0C1U26C8dKqFgxvqW_TJH5Lc9F0W8ia4tBCx5LSONR55XfI18e8fS1EnYVpVLKl5XNQj9sLqHlWikA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "나의 행복한 결혼 특별편",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/auvODjznZbPqAc1HzlAAy0wjgK45rSOP0n2ySSgrVRHIZRw2-BKfkZvXdLaJewsO9y9j_YZKgDnn3YmMZh01gA1S-Z7xWCkea8X1yc6COTCCwz9vdI00fDPFWzurpEdFxfCHoOGFlvXWkKmfVkBQuw.webp",
    "netflixLink": "https://www.netflix.com/title/81564905",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "낙원추방 마음의 레조넌스",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/8NTZ6ZKS9V_JuCoK0vZR3_yCSzDMlAdnhmfdgUGSFs1l2NIuOkbo97tTYb0J-wk1olBHTERqwf1AQ8A4H0e9ha3J-yHhXkzxlaYGBhOmpSi2GFLAbkei8Tf4-JAhO2bxBFtdhoHCZ5Erd5ALd2xpYQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "낯가림 심한 미망인 설녀와 저주의 반지/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/SG6i5sG6ze5CZYAQ_embWXKrMonfvg4teBhOEBfZQBPJnuIgoVMPgEINyoUqLUAOMq6PRuXouavRMTP6gaU7PUvbgIV6SEV0faBxc3VeccE7jXjPA2YPR0OuD_1QgvX9Hhyy1Pyhm4l-BTlTiiXBFA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "눈을 떴더니 최강 무장과 우주선을 가지고 있어서, 집 한채를 목표로 용병으로 자유롭게 살고 싶다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/SXXRpwOBjt6bnyIQuhUZY9ofbF8uLCiGu7mLWYUfQhl_DjGdrRX40N8Dvs5-alD8FQG58AMPJmYraJbJg-04PbS-UIq5VKp_Ytd1ivcd3mThPR0wOLAgcnP055ZSpOVYh8gsYl-BFgGzRv_IYXtgxg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "다이아몬드 에이스 actII -Second Season-",
    "year": "2026",
    "quarter": "2분기",
    "image": "https://i.namu.wiki/i/Wx0aFyyUjmPHMD6DJP7xKDaF06aXzK1mX4qQfl-m08JmoDcEHI7OvGdc4P6BTNKJ6ag_lofwHfN_feQT8uI9R63TUU0Wtf6RRF2cw73hdat-0pmbgL44-d1BYOIYDDc-TulQmQWou5M9BGfUmVsIfw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "https://watcha.com/contents/tRX5x1Q",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "다크서머너와 썸을 탔다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/U5TbluqNaJvQy8HVBumRrKRmvY4QOboX6ixK7A_VMl0tVhwn2Uk3S2yn0_i7xlUSE9wT0r5vicPQypdQ-E0fw8GlZOreaoaem4bcm06mu4to39ZJatptyq8w8JkhdAGDVyivntXzdgYdqiLrf8hDLQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "데몬즈 크레스트/애니메이션",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/tiPi6CMoaxmvWoVAKRSy-RAJECw4mQdJ2ZMTHqZsW6OAuD02V8Bb_RbxdIevvICWwm7BSUJBsOCaNs97uD9p9S-kqU69HfDgaWckCyp1xfVzUMHMONkEKLzy-0vQt5vXZmiCcSDMYWNi7qaluCVF2Q.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "도원암귀 ~일광·화엄 폭포 편~",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/5eLtOL-ahbKpTeLjXEF74scY_CUKunG5MSOSknhdprgww0bDKzTKGGSH1HaKv0TNx5OcHuitUZRjv3LaUoySdOluTZjAnQiu9RUhBgUhlMMGjY2hoRHPpEyr8h2ZmU0qp1HFU7ufHZ60FvnlCin2NA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "도쿄 리벤저스: 삼천전쟁편",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/Yl1ndynXvJE5rlyt8GLNfkvZuxk5ZDXna3pYC_vEsBSGPJbmeMOx-jAzVUxJmEWCH_RvRslWIwa_UqbnQa_b-hY90Q0g3--7Lj9SYpsWX2-Iqf100ySggEPcmsoiFR8Z-6C1mFkO1RKE-zA98MOtiw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "듀얼마스터즈 LOST ~단죄의 소년~",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/5l9ePTFzB5xyi4wJYkSIhShEMyPRcN2BcAvZ3sQpNF_2FsrmFU_qLy-QYRQPvDPkVV3mdjVYpBve9ND9KycKu1DzTFNwsbZDpigmkiSUGEYwQFrobpQJiTmJTKyEkaN0gCsqpUeRWMTNArSPUMLmXw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "드래곤볼 슈퍼: 비루스",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/eL6RdAMpLovAbe6xRdvRHRiA18Jpq_YwZPpgbBfAw3bIB6BbC05QQopsh0s_kAbxXN5aGM9H9tPKJtOO0oac42QrerUVxRRXZVIJh_mySJ_EmIptRFihEyPHJAn8J17VndqN0y4O6C_yVjX45t66qQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "디즈니 트위스티드 원더랜드: 애니메이션",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/jwZs8f_VWJ0e_2EQ9MI47QE_RkUWnSdhqPfklQLOpltZvX83DiJ2WL8Ix4aVm8zLIrbodz6PE8u4HtmA6hMqLNJZCtYuWhFWTmqYZLuFA0du19mTF61CxtK-eaK88V1DasZ5FNb_MLVnvBijcTR0JQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "란마 1/2(신작 TVA 3기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/EEhID6H_QyVtEyxhsQBD4fzveAWqh_3QDhWq-c0dcdieO_gRkIgDKqaDgD0vF78R1G0Z2bw8FlGZjGuDPycBuX5wAXggzIjDGOukVgO4YsiCwkInfn7WeAzvww3Z98ZMFHMALECUnOaTcdc7vC91-Q.webp",
    "netflixLink": "https://www.netflix.com/title/81171925",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "로멜리아 전기(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/dqRO8bJjOa7y_pGWN7gDdwiiR8nFKNAJBjeHvsigTkdUBrh6WUZZlNIsIt3sq0caHLEhpivOmp9IKoWVbGyItnF7E9nLFnEDFWtCTGWpMVq2qS9eaPJ4R77TIsCYc5MSdod6tj2j5jjebwwLo1cw3g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "마로니에 왕국의 7인의 기사/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/CHSOv7l_IW7zQV9_jhjgHhmOX5XSH1UiNYRXlul2EdCmtlEyYgHCTSNe2mCKJhX0lDgyW9_NpwlSvcC2Cn0_J55U--sxGKFhtKJ1eWQIS7vCaXUSVFykk59epBmh4uofhrZHblsSPjhNZ7PRdbO44g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "마법기사 레이어스(2026년 애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/3snbwQJoNADD_q66v0lXtoLXApufSbtEjZ-4bZhUYbcKN9DLekqmFAKJ7b5cibSL_A1TweMykYVgVL6c7FoWcfWDxmMq1htrgiNFYmxlpSdr7t5P_K3WatqC7oDNmNNyKuN378ps91GDVFqLq7b5WQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "마법사의 밤/애니메이션",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/sIsPRrdHrB51n0j931r-TeIUTtMcVCh3jB_gy5YGIsl0I1bzd3Mc5v8JObAYZ9-aS2sBfFLIXX4w6ilD4lbc7TzYQOPq759EeNQeG-Xclw9_DdHHY14_EIvS5hP_6okSbL0hwMRpsMqXenQjzK7uCw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "마법소녀 육성계획 restart(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/Jh6w6QptoEYTjUjDoI1KIExgwcMBQCF7TA04-AZBvfggKffaC17QWlcvKW7igCLiZxwCJCEPZ4HV3uLtMaoLlE0PGojSz3UqUonVReDTO63tOmmTG62-cp-qg3_M-YFSUv0x67TQtInRj67_q2Q6TA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "마법의 자매 루루토리리",
    "year": "2026",
    "quarter": "2분기",
    "image": "https://i.namu.wiki/i/CQX1qzBX9bP7xUnGtDOWZQfAMOSENMOrn8Ck1mYHnrb4tCz5huiKXvbJ4BDeq-ul1r4t0C1MpMgX5cLdCOtbuIyj1xMXfvLK75fYisFV1mqqDR76JTyRUHFKsLVpcqTXgy5olvs_p2weAQyf7tv7ng.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "https://watcha.com/contents/tEqZ5NY",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "매지컬★익스플로러(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/FBIlW37p03f50UFkBz7R9f-N7y-d9OAp1Ax7xX-BqY5TMf74SdhISFTdbKlo1Ih7ESFqQbuAiHhB9nf1ZMs_4zqSRcpvGhAZWizQ90r34g59-2lmVR4TjrePhC0ia9qHcIDORGdomXHrB9zNkF04rQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "메이드 인 어비스: 깨어나는 신비",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/o2pc7_I87Qp_G6N4RRDEdYFFX5WyvWz6k6--sLhMZEamKgJ8XDjvTdvNoscqVepRAMvKMaSqbGlvH_9hTmD4H25CoSRNxe2guvfOw_hf9_d_fugunD6Wk2FEGqXgaoa1t8qvz7aWJr64LVi7kyeHMA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "바람의 저편(만화)/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/FOWQBAj14sIC8463o1pudEaIaq91r-87ZgmtUWPcJLxLxg2Gi9WbZIL05fqfkADGJjCtTp4b5KBI2JOdNQztd7xkD4SYAeWAjY_QZjcQAmPxkvLa0-2XUfc7EkBOlzh_hVrh9-9628OqJS-_DpL78g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "반딧불이의 혼례/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/5zBNcNbFPArtzOLaJzfLvz2zWgFwdIAeFc2O5HcDmhr-43XAZ5bKMKp6Ih7IA-dhF8y6gMEqcAW6hk7Bl2Uua8pDFAdKm_qoart-ouWE_3xL_rLoX5QtiaimyFjpMfH43onyqy0AeayEsWTPubHIRA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "배틀 스피리츠 [Re] 절계의 하늘",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/HkJnUOQQO5N27jArciHoyBwgA_n9zCGTSyy-bOsvB9LelHI4xgdJq7z8P1r-RJwLpK-XW5-Vwm3Ljtuk7swBTZ1Ao9Q6gzg2xgZOV1rEvQaZ2-qRregAFxzb8zFxQC4ZzwwBQFYfqjS2jnfMR3JvEA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "백요보/애니메이션",
    "year": "2020",
    "quarter": "2분기",
    "image": "https://i.namu.wiki/i/i00YdKWeweSw9Z5OMDlSRcurhDFIsT5n5IdFFt45XYaLXRau2swTJFR9enUegbNsSS-ML7HKaok23fT0GNvcWKV0YfY-JgMrbsdIL3IqQzXP9TPf_Jtdtez9ZLBLAHOrZ5xE58UJgYP3H-GzPxR86g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "버텍스 포스",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/DQqdWK5wJc0U7wwBa4Dh7PSSGuAIkJt2sS2T0pdSK_58X7uRSJCrhElUiZpujyFnW7wOSTGnCLz2XUXPOtyLmDx7qespcbTFwO0liG_RX-hSeFvY61LAGd8LRMnsEe2w7xh5GAyiMZpj-yBlLEW8bw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "베이블레이드X(애니메이션 4기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/IUbM_PM3oJZV8zoz6XP9_6iS7I23_Ynri56gT8nWFyV4h3pl9Wypz53qQPjiYEHth8nwpsUc8ysAA9ktc7WPnSwETFHQ7NJXYAvwa3Jwh4sPgWZj3EgZqWkbIku55S40KSFvEarAzemj_0b3rlSonQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "블랙 클로버(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/HhU7gFKF7ojGeX2VoE7gnnTWrREcr8osx_D8IyXfkMOPI7s_l-58BF5yYsR5OVgitK-XsFRcwCdtVPPM6E7FZoe7QNYbEeIKcZPg_MU2hbB4KeAV1r6OABXXF2oyFACWP__VcFwZKzb9AQy65GvSww.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "빌려준 마력은 【리볼빙】으로 강제징수(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/-zbu7PhuoiSaJ61Lk-Xa-bl98Yjf8JPcFtSNxKfIT5amPw7y3Dx1gxzph1PMr9WDVY5ViGDWzmdI551GdC6EDyj03ST-eVPIhiDycpI2_bXL9aQ7Cnp7A8ngZDk5hzK9G0uc-s-iYTVmDmuR5RAKnQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "빙검의 마술사가 세계를 다스린다 Ⅱ",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/XnzhmIv391q6XzfkSmfW1wMBzbSt6AyWQcOSUd-ab3L02SDsEikucEOXpLRlzRtgmomVVw-vxfSYLT0Tq3bLGY2TsFHD2bec-xUwaRk3uVPFEkmkqyRU27Y4Yc7ip1Xc0Q-5GyL4OSDXQq23Z5cZbA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "사사키와 피짱(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/8IS2rRfjwofogMdEXywHaZZUK7DfPM9f9j90rKDst2vDUUPRoLDlKTkarXXmJkSpjvmtNNmeTBwSbXOlp3KJGWGtV3DlUgK0cUCdiK3Gvs9S4ygx5zcLYlwwKy1rjyIDQ1UXgugE1ST6cC7HYYpykg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "사이렌(만화)/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/ynP1IYAgiWDNEwChK-seDOQVII76vBNmjj1fl24jToxdcJ6F6l0kulxauNzw9oO_9e2z4ZlNCjZ93Hlv2qTc7Xl-ObLc_WAPfKjpJ98IvpJxKjjIQuL_658R-wrTge3JmuaozdphVHa8NLVeg1NMaA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "사이버펑크: 엣지러너 2",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/8fDYwdiqrNscnGz37iBBlZiON-7yV0nmQkWCTh_EGMATt1Je5_VliY56C-R8gIUr9lctFFIN8T2qkFnaPZJRa_rQadDCPl06ONOUudb1KECWqKgltUNe_H_j67LnJcD4zdqQRAKhjJEaUexj5dYIUA.webp",
    "netflixLink": "https://www.netflix.com/title/81744226",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "상처투성이 성녀로부터 복수를 담아(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/I86S-3zMYmR3fMIgG8Eg6PSang30DSiXQKxvTqFdzK7AP5RUGAIrnntljSG-gGjwB3OpixRfGO4OQwvW0diSyW-U-qrcAF3aoHt1YLQJFUu8-O0pl8I9wE2_cDoWYLKMUUl-15O902BhkPS3A_6qmQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "세계 최강의 마녀, 시작했습니다(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/xmAiugmafFjp_AedWKhlVCycYkvmfBkCTIeUjFduwgP3qaIrLHTrfj0ThK-P893mJh3F_Zfq_7J8S3UAviJDREVCR-1-Eqevf4mDitXLVNJZkpJQx3qGj4xa3o6xt46Kj0BKoKaNiBgqb_DUw_HR4g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "수왕무신 댄디바인",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/FLCLme28UrauHR_YNXvp8X-zEIU7MRQKZm-eBJUqeCXHEftP2yBnCWBXpfVZ7rQnxxIYLEQQbLWKyY317opQ1wf3mDFxF8gwH7KseYlMmThIDQ9LuRpAn0pq9CYlSlBRUVHNTk-SSNbeiJST5TNRrA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "스틸 볼 런: 죠죠의 기묘한 모험",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/cPI-gM5atywnb8SYRid82tgNArfJbiO5dqiTe84fu8OZ3ejpWAY8q8o2b7U_g4a123mNsDcb5nOWVrUn9Dze9ic9VSHJkZr6aq3Onuj7yh1lCnVfQ5l4SryhZV6aJbvoCx_FuQ6BUuZxLRZmF7ocAA.webp",
    "netflixLink": "https://www.netflix.com/title/82116553",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "신 테니스의 왕자 U-17 WORLD CUP 결승 멤버 결정전",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/g-XK2nyqdd2woZ3cfa1jlbT1OExm3nyHr0DCpOCQa2NM7l5SvtsRqVG9cnzpt7TjSdsDeM54i_bNguVqI7-Z2Pry0GuuCVXXI-qGM24w89EpdtLdMU9wTdFNX8HMkAfWu9ehTUeiaIpA1IxPlQfi_Q.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "신자 0명 여신님과 시작하는 이세계 공략/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/CadZxYVybzAxwg4U4cxTsN0YYiv68hWYkg6TcD8kCMjaPUL0uhMukSfhwjpB3sodaxhHNg6WZyiXf02OJebrnd5BPvizU3q2qMZGamJV1ylhcniDUS2A2PHW7XREFTCPZMMfG1kSpV0EA-L_BtVBDg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "쌀쌀맞은 사토 양이 나에게만 상냥하다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/64kGdltI60z71bj54stw8X3ZdXEK38QHE77prSEXKHEQEO2p3WMVJl99AKWQpZ-z5i22g76MkuIBsNqFw8Bs3NVNIY5qkVMelYQHgIirtWrNnmvgehrgzvrJyehfFRYCMLZS_Dx7776GF3QxC9cXxQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "아오아시(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/51q4Mgbb8RQIcuPXCn-55itstOH28eHfZzVV3hgKaNTc8J0ysZpEIil_HsrlSTVgvwH-Wp7r4Q_XY7Kz0PksLA9Okj-9ZQnVdDta1sbfLxVxzdKqPQixuHHWRq4e8vcS1ehPqUvVjykGu93NdjAbSw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "아저씨는 귀여운 것을 좋아해/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/6tz5r7ef8h-iHDzDvyeyyEjJPpUzlxqpbSvNwdvlMT_th2j8eoSVokzFhvxPPfoBwYd2j_YZACToM9ivDkzFz4lVGDGHF5zprU1T5pqJ02EnqzsvzXEnkgUbmjWGKv-7Bl5k5pKBb4-vpj-RuFq8kg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "안녕하세요. 반한 사람에게 사랑의 묘약을 의뢰받은 마녀입니다./애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/K76mmIEfjDnpVqLO3qSuL0nNPj_aWvTxFXX5UDcs00A-PTQZzi35tjwtSFMdwTo3xIjG-r2Np76MGXNvBa3d5ILYqfwoCubpkPo4IGg2vkx8Olw504mwjV04wQZdAwvNMTYQo7mva8aipEnklWoR0g.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "야마토여 영원히 REBEL 3199",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/A95KR1HafPOwrOVM9BXYaWnzoQPznha603sowFzhhNEkFQ8GzHyRT0XvWD-fYUI5XXbU0Ue4m1cp1zBfFkGF8iIei_I7_Uyj1FWZ9DSRNa8myFwhPJQILWskCzmx8zRWXlcps34T1WSUTVACw3I_Ag.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "야생의 라스트 보스가 나타났다!(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/Gvp6b-vKYVUwRwNv7zCSzO3QyNEUUOyaZYFXtAcyRkPOlWcO09quIMf1iJBGdR6GHMcWcoblusXbTAf9MaPhZgEpVa6jNy9vJV8yAH54BPkv52u6lg6isc-6Cm25l78nqheowVWJ9E7sNgRkooi7HA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "약사의 혼잣말(애니메이션 3기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/pR6TX3ARxU2R2FpjjnokjH4fzjRg7Pvb5b2fDOyQftQfhk929hCS-8asZfGjANkCJ9hVyRUrw2bHyNVcoshGBYdy2CzVR8KdvLoPv_1OtAt4h7OK8WZHEuXqz9UI9INm2-SINmjEoREorQef2KspFA.webp",
    "netflixLink": "https://www.netflix.com/title/81712068",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "어떤 암부의 소녀공서/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/BLme46ltvtmSPGX727F0VAmcUJpQVcIIvBLMeHjGmoBGdiLhhJ-0Kve1FxYjhRRlL5YWD_gd_qgWEvNLMAqlvKGvQlu3CvQPeI2MR3_h8udXlFEZXtvnNtnWmNuyFRhaDf8O7RP1LgSsCBVUM11_ow.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "얼음 성벽(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/7oYc-8CdhKLTE_O26CeU_AbVFteQfq8X8irL3reYPZieEEaGrJwlYKxLKXr-HtPyZuyJvG7OP-eCmhoo-rpFsS-pfOOwiBmll4IzzFfqfKMIv1L5kqa_MmqJa7oES9aUcDZnA249aZVJdVXhH-VB8A.webp",
    "netflixLink": "https://www.netflix.com/title/82031882",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "여친의 친구/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/UpzOGJi9NEry4fLkOzrJsoG_36RT_J91LtCsuLT3xQmU99YGtIutTMnxPjTRalMAqPHEriiz1-4-5axWcGtj7AcIR9gVHdnqWXhHOH76YK97BmezK9jchUi5SUZxrlMsO0x5R0gPiiht2aSaQpLyWw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "요자쿠라 일가의 대작전(애니메이션 2기)",
    "year": "2026",
    "quarter": "2분기",
    "image": "https://i.namu.wiki/i/C985Nb932__4is2TvI6Aj06NKJOxDYXH1Lwh6d_OIDGJmCaTnKSTOFvey5b0PeuT0fE8USVYkBJoTAUv0wMqeJq_zMe4jtZU3IZWb_sPC4EMtL64Jc7kCj72eIruyQJN3cAm3sm2TrwnjzphcxXoLw.webp",
    "netflixLink": "https://www.netflix.com/title/81766575",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "우리 남동생들이 죄송합니다/애니메이션",
    "year": "2026",
    "quarter": "3분기",
    "image": "https://i.namu.wiki/i/CutMroUvHE7put3qQ84CV0MCeMyB3BiXoYl4pUienwjc5FKaSicpmzwDykyItkxcVYcR4D_Oiwb44U-k0G59Hxbc3mhIjb4y9cPOFt38VNjXMTTyJDep6bc9dPkYMQ_bWd1Th5TCpZSrHD_Te6xaOQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "장갑기병 보톰즈 회색의 마녀",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/qWrkrPRqFKRfLk4cUf6Zp6wQGhj87nvwUHcg2skDwt50k1xZHG1N4ulazulSosNPtH5uoEHeQtXQNsmBC_eYuQZkXZaQoWdYnaUMt7s9OFv4fAz4GPwWa8rTtr9UJXm44Nen5AzEgWzLaURrslcRCg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "전생 고블린인데 질문 있어?/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/85hqOptZhk7vE2byjuOhSAzUwE8yuSdGJQGcA2c77PiOtQIuPscxNWl2T_v1hEuCngNYgTTeR7B-tn0PJBPpOdgrD3iO-pwQESsLMgzXAKTL1LPM-263YZGcw8sOv-6hYfmz9W86E_0_z4XfnLKekg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "전생 귀족, 감정 스킬로 성공하다(애니메이션 3기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/I1MAbXzfNcb3i9NGa4M5SPek8te9eIhgnR5tf5D5cR6ik0YSFupLjgWDn7AhLnoF3K3BQYTFFYYWH4jJIaI4c_W3gwOWWsLJPze6VBsK5fCWlJ51N_4_mf4CTFjxBLz5TXYt8g_LZPMgnnsf6DuOHA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "전생한 대성녀는 성녀임을 숨긴다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/6gAgTaxCtVAUvyQsT1GFBTAfKfwToj-T2zUOlohJ8B2WkuItNllSP5bax1is-8xxX-V_Rm5thXG37rUHsah8roNVbpBoaoTMFA6rDuxdwkqMk3Zl_fDrsd1EcalLf4hYLDsB93rsJlDVwpZF-mfZBQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "전생했더니 검이었습니다 Ⅱ",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/6GmEr6VbO-BGDbvggA-lxFLBR8Ntb37VUkhFS_3iEtAgB-tvARmCJGMoAxgphnupHwwc3jyeDcPG1KjUNs1SDkXilinITDjx4k2caV4sYpofI3cEIXL90SgKF9a3Hi2-yhyWLpqmZ0qWQqTaB5wUAA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "주홍색 가면/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/SVXhVgo6K4yPKZYNYSoVyJZyM3lZ1F83l7dj0YDChuVreS1DlzdRMRjVV0QgbAcHmw4WvxuVjhB0MqWPQh9rpU5KveNH7_7CH_58uE2AfTTyILIN41jmijiyC15o5EV3RNfO2BPQO20sKIhlhV6Cbg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "청춘 돼지는 디어 프렌드의 꿈을 꾸지 않는다(애니메이션)",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/drFxk4ikUGYXJqfk1YHf0UFX-ujmx2UEzAYY7OQ0tEh4DJbZAOyEXC5BQIxVsrS6Hke2TegzVcV1TBnju54Ii6aOCMXM1H2GrEkq_o_PYhPEHEKJcRFk37Ualkc8ed8gCje4dQIMw9esFDJggPBxeQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "초능력 순경! 쵸죠 선배/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/HNELX12r6kLga0jm7nlGRqX_iNZD7cRP0tsN_RcDKiiV0NQqfAarorLZcEYJtuc5zQwGYBpjWpFe8wm6e9Et2wqQ_vXEhdfym1o-aI6t_RQEBfXb6d17zuIcnyDOnrMPzVXgrOvtuQENmXsUR0iqvA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "추방 당한 전생 중기사는 게임 지식으로 무쌍한다/애니메이션",
    "year": "2026",
    "quarter": "3분기",
    "image": "https://i.namu.wiki/i/Q2hlrSuvTWK32hodz76uJqhSMnxa80i26pAdGCyKzmFE0QnS2Qaa9IYxRQ09oiy-uTphggD1iraAY8fL_ZE5qYBWBbxIuxaY9WVH1K-5kiZ0fxCiTHqO3BUj3R2kLm1sbFjMpVw2UQJt7rjyee0_Cw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "추방당한 상인은 돈의 힘으로 세계를 구한다/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/8e8__gEK1wCafBegROf2u5d1tOFGpuPvtA5kYm6AoLGjq50clNQA9bFkEA0sv92M1hpbnHjbdQ1fRv_6aBSAzJIhiZymEMMA3NtxFUbZA1AxnZur1xFmrfM1q7DNeY72FgR1-BDPFmu0hhYZDbtUFw.svg",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "추방당한 치트 부여 마술사는 자유로운 세컨드 라이프를 구가한다 ~나는 무기뿐만 아니라, 모든 것에 『강화 포인트』를 부여할 수 있고, 언제든지 효과를 해제할 수 있는데, 남은 사람들은 괜찮아?~/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/yye39yqTH5WRiJv4Cz_JXvR9rpgQ691QWHkOURzI1JtheNDkdGKNnw7cc5fzu71eRjYFNGWN2ESJcRNMM47tKNcCpWhdZVmgk_2MDbaIJ9xj60zMNI9bpXYqeS-sR7m1s3ekUb94K_1s4MaXMugvgA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "치토세 군은 라무네 병 속에/애니메이션",
    "year": "2025",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/oGPH9yvdU4pJc6_HdhSwDfdEPmv58pz8dYsn6h7t7SVPpxKyxio4Dlrt1eNhorfTR6ccHen-OlF49Yy4IMXQaES-3IA1iz8u8V5u5AQMZvVAqa6qvmxIA_WAqGWsoW_f8x5Ns7mzoohy1-JB_Z2LKw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "https://watcha.com/contents/tR2eraW",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "카드파이트!! 뱅가드 Divinez",
    "year": "2024",
    "quarter": "1분기",
    "image": "https://i.namu.wiki/i/owc74Oyt0ZMWmstmfiuZD68sy9bvG7Kw6cfRn4IXQNB3ON7fMDden7E4P6nSM8vym3gYlW1krOZ_kvpA_x5qM0LnucAfugc0kxszBMWJwyEG7osPenwOY6lh7VoxP0nSwlcZhrHBMbHL2Foy7QPywQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "탐정은 이미 죽었다(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/5VfwHV-hJVg0TK61DqZeULiyooNZMUkBdSyXtJUfSTbFgrLgoosITDHGMn0uSgCzt3xjjrlFOkpSh6WkIxiuto50DY9nyl3YNYarQ_XKHyv6NJDa5w0PXTCnQsqOR7sZPfvISBF0b7VsR1I96dYllA.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "https://watcha.com/contents/tlnN5xO",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "테츠료! meet with 철도무스메",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/sjPF_fupoRVXG-HQjvv_732gw0-61_zU56-pqk8u4Z5MnHh92XzCAmFRYwjK4T5ZeOA4jSS9sZt4F3wWwXa0x0C8EEYIShQP0iTlR-VWY3PtF6v37oQEwKiwSLjuVR7mad0uObFr250xFW-5906GLQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "템빨 ~아이템의 힘~",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/lKrOfh9BOzN-qdRQd22FIzILBJwtZVgvX1QjuYCoh9KFPY8D1P5uIYJl6PxvlFs4x4UWizu5mnzrkaHJGbjlFaXmT-yXTbkhkwr9rJb3uBQxnbTMFgNoFequyBKZzGIi-4AxbXZZvKk7jWnDnQL7KQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "푸른 상자(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/DpsoHhfK9Iapi3jMdAKXNLJik-IrIcFSXnKcRuImbt0BgmaX6jVAVRNsvwSKk-1EZhThUZmarbr9uFweSsraAA7qLOOAxjVUYx0CsoOdXErqmXscd92pahFY3jYv_2le6ZaKPV35MrmMr-W-pK95vw.webp",
    "netflixLink": "https://www.netflix.com/title/81663323",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "푸른 전승 웰시와 쉐다르",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/UrMir0ExFkInN-_DOIZcvEEa1_Bp_cblUyd68nJJwPk79OtKrX7T6-v4ERKrV31HFu4sfDNh3Kas0kp6c182lng4vsXh2HpLqBfFnk13W2yBnmM8LlnI34jBmsxIPFqy6oB4mg-1j2CumShwbiE3Gg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "풀 나이트/애니메이션",
    "year": "",
    "quarter": "",
    "image": "https://i.namu.wiki/i/KkVgDdQpqnNBAqsmm5AztjBNW1t8rvTBukUQjxBhzAFvoDbn2NWSkvmRMc4_AfiIgcB21n6IVfpYmgJtYVwYfvweqcB3vJpoqEiLngHtBUI2CSY5SL9-4sS1LqhPADv_tYdK_yJCiMuHIJtSjHBcNg.webp",
    "netflixLink": "https://www.netflix.com/title/81991076",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "하늘은 붉은 강가/애니메이션",
    "year": "2026",
    "quarter": "3분기",
    "image": "https://i.namu.wiki/i/gwLl-2uG6XaZ0Cbf3RQ7wlS8G7WJtE2948HR9S968QQFyUFtr9kqtRjizZFuK7G0cj2egtr0YlbmwZO696QgJXGOCOPWUke2pKalEPBn_cYtsJkO1f_rrJ0XEXGGL2mewIenzDf9F4O_JuCt-mx8bg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "학생회에도 구멍은 있다!/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/BUaTDGnRKXgU1W9y8796kmF_7Xr-E62n31M02rYh6zTi8p4na_JNI7BuVW-PyNRV9OynOpQ-NMCk5R49dHzRV-kGYPOqgIpuUUn2_8l2lAMrw0pzg6ftSdDKZ0YunnRDIXHnixY6Y3yFqpEPAXhtOg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "호텔 인휴먼즈(애니메이션 2기)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/NFJ5Con4c94asr_blf_C2sjTfT2XFp6sTz8QGc_yen1BYdQt0cs6-11ORHQDmEaU0p67Y08jx2ZutL5AuXj2hfiStUigvvXR35MvXYR3PGrp3LXj9hvVv8XHt59aL6sA1PweMFUIx9PMh5u-TeUbcQ.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "환상수호전(애니메이션)",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/Z51_-Ng-_Jp6Aq7oLtOg70EgcRCJu5kthd7Mpz3UR3jO7W6mzpQTg2ImskxvaeCEkaLG-gwglBxj4sZi5zIqIFMg8W0Wv1a5N_8qqpy9vU_uOokY9mPiCcN-ExJTK9koKkBShGk9BbpSbY_pwYrCJw.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  },
  {
    "title": "흉란영애 니아 리스톤 병약한 영애로 전생한 살신 무인의 화려한 무쌍담/애니메이션",
    "year": "2026",
    "quarter": "4분기",
    "image": "https://i.namu.wiki/i/O8gLJGoWP1ZIIqLXuP7TW68E3T40uCveg-qevnsRd-s1Bk2_cHPXVtj3Nd-gwpwpsqtEhlVDLjmsZpcppprl1mRXALW4Pt8fZhcKRKCLscIrn1xVCkHGlHZilV0is6plvj91YSYK8zx4qT4kHVLrKg.webp",
    "netflixLink": "",
    "laftelLink": "",
    "wavveLink": "",
    "watchaLink": "",
    "tvingLink": "",
    "coupangplayLink": ""
  }
] as const;
